site_name: Worker
repo_url: https://dev.azure.com/EFSCIS/EFS-SDK/_git/worker
site_description: Documentation for the Worker Repo of the Superb Data Kraken

nav:
  - Home: index.md
  - Architecture Decision Records (ADR):
    - Template: arch/0000_template-adr.md

plugins:
  - techdocs-core